<?php
namespace google\protobuf\FileOptions;

// @@protoc_insertion_point(namespace:.google.protobuf.FileOptions.OptimizeMode)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 */
class OptimizeMode extends \ProtocolBuffers\Enum
{
  // @@protoc_insertion_point(traits:.google.protobuf.FileOptions.OptimizeMode)
  
  const SPEED = 1;
  /**
   * etc.
   */
  const CODE_SIZE = 2;
  const LITE_RUNTIME = 3;
  
  // @@protoc_insertion_point(const_scope:.google.protobuf.FileOptions.OptimizeMode)
  
  // @@protoc_insertion_point(class_scope:.google.protobuf.FileOptions.OptimizeMode)
  
  public static function getEnumDescriptor()
  {
    static $descriptor;
    if (!$descriptor) {
      $builder = new \ProtocolBuffers\EnumDescriptorBuilder();
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => 1,
        "name"  => 'SPEED',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => 2,
        "name"  => 'CODE_SIZE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => 3,
        "name"  => 'LITE_RUNTIME',
      )));
      // @@protoc_insertion_point(builder_scope:.google.protobuf.FileOptions.OptimizeMode)
      $descriptor = $builder->build();
    }
    return $descriptor;
  }
}
