<?php
namespace google\protobuf\FileOptions;

// @@protoc_insertion_point(namespace:.google.protobuf.FileOptions.OptimizeMode)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 */
class OptimizeMode extends \ProtocolBuffers\Enum
{
  const SPEED = 1;
  const CODE_SIZE = 2;
  const LITE_RUNTIME = 3;
}
