<?php
namespace google\protobuf\FileOptions;


/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 */
class OptimizeMode
{
  const SPEED = 1;
  const CODE_SIZE = 2;
  const LITE_RUNTIME = 3;
}

