<?php
namespace google\protobuf\compiler;

// @@protoc_insertion_point(namespace:.google.protobuf.compiler.CodeGeneratorRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/compiler/plugin.proto
 *
 * -*- magic methods -*-
 *
 * @method array getFileToGenerate()
 * @method void appendFileToGenerate(array $value)
 * @method string getParameter()
 * @method void setParameter(string $value)
 * @method array getProtoFile()
 * @method void appendProtoFile(array $value)
 */
class CodeGeneratorRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.google.protobuf.compiler.CodeGeneratorRequest)
  
  /** @var array $file_to_generate tag:1  optional */
  protected $file_to_generate;
  /** @var string $parameter tag:2  optional */
  protected $parameter;
  /** @var array $proto_file tag:15  optional */
  protected $proto_file;
  
  // @@protoc_insertion_point(properties_scope:.google.protobuf.compiler.CodeGeneratorRequest)

  // @@protoc_insertion_point(class_scope:.google.protobuf.compiler.CodeGeneratorRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "file_to_generate",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "parameter",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(15, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "proto_file",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => "\\google\\protobuf\\FileDescriptorProto",
      )));
      // @@protoc_insertion_point(builder_scope:.google.protobuf.compiler.CodeGeneratorRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
