#!/usr/bin/env php
<?php
/*
 * This file is part of the protoc-gen-php package.
 *
 * (c) Shuhei Tanuma <shuhei.tanuma@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
require __DIR__ . DIRECTORY_SEPARATOR . "proto" . DIRECTORY_SEPARATOR . "autoload.php";
require __DIR__ . DIRECTORY_SEPARATOR . "src" . DIRECTORY_SEPARATOR . "protocolbuffers" . DIRECTORY_SEPARATOR . "Autoloader.php";
\protocolbuffers\Autoloader::register();

$stdin =  stream_get_contents(STDIN);
file_put_contents("dat", $stdin);

//$stdin = file_get_contents("dat");
$compiler = new \protocolbuffers\Compiler();
$response = $compiler->compile($stdin);
$result = $response->serializeToString();

fwrite(STDOUT, $result);
