<?php
namespace google\protobuf\DescriptorProto;

// @@protoc_insertion_point(namespace:.google.protobuf.DescriptorProto.ExtensionRange)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method string getStart()
 * @method void setStart(string $value)
 * @method string getEnd()
 * @method void setEnd(string $value)
 */
class ExtensionRange extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.google.protobuf.DescriptorProto.ExtensionRange)
  
  /**
   * @var string $start
   * @tag 1
   * @label optional
   **/
  protected $start;
  
  /**
   * @var string $end
   * @tag 2
   * @label optional
   **/
  protected $end;
  
  
  // @@protoc_insertion_point(properties_scope:.google.protobuf.DescriptorProto.ExtensionRange)

  // @@protoc_insertion_point(class_scope:.google.protobuf.DescriptorProto.ExtensionRange)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "start",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "end",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.google.protobuf.DescriptorProto.ExtensionRange)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
