<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:google.protobuf.DescriptorProto)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method string getName()
 * @method void setName()
 * @method array getField()
 * @method void appendField()
 * @method array getExtension()
 * @method void appendExtension()
 * @method array getNestedType()
 * @method void appendNestedType()
 * @method array getEnumType()
 * @method void appendEnumType()
 * @method array getExtensionRange()
 * @method void appendExtensionRange()
 * @method \google\protobuf\MessageOptions getOptions()
 * @method void setOptions()
 *
 */
class DescriptorProto extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:google.protobuf.DescriptorProto)

  /** @var string $name tag:1  optional \ProtocolBuffers::TYPE_STRING */
  protected $name;

  /** @var array $field tag:2  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $field = array();

  /** @var array $extension tag:6  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $extension = array();

  /** @var array $nested_type tag:3  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $nested_type = array();

  /** @var array $enum_type tag:4  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $enum_type = array();

  /** @var array $extension_range tag:5  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $extension_range = array();

  /** @var \google\protobuf\MessageOptions $options tag:7  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $options;

  // @@protoc_insertion_point(properties_scope:google.protobuf.DescriptorProto)

  // @@protoc_insertion_point(class_scope:google.protobuf.DescriptorProto)

  /**
   * get descriptor for protocol buffers
   * 
   * @return ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;

    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "field",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\FieldDescriptorProto",
      )));
      $desc->addField(6, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "extension",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\FieldDescriptorProto",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "nested_type",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\DescriptorProto",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "enum_type",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\EnumDescriptorProto",
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "extension_range",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\DescriptorProto\\ExtensionRange",
      )));
      $desc->addField(7, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "options",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\MessageOptions",
      )));
      // @@protoc_insertion_point(builder_scope:google.protobuf.DescriptorProto)

      $descriptor = $desc->build();
    }

    return $descriptor;
  }

}

