<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:google.protobuf.FileOptions)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method string getJavaPackage()
 * @method void setJavaPackage()
 * @method string getJavaOuterClassname()
 * @method void setJavaOuterClassname()
 * @method bool getJavaMultipleFiles()
 * @method void setJavaMultipleFiles()
 * @method bool getJavaGenerateEqualsAndHash()
 * @method void setJavaGenerateEqualsAndHash()
 * @method int getOptimizeFor()
 * @method void setOptimizeFor()
 * @method string getGoPackage()
 * @method void setGoPackage()
 * @method bool getCcGenericServices()
 * @method void setCcGenericServices()
 * @method bool getJavaGenericServices()
 * @method void setJavaGenericServices()
 * @method bool getPyGenericServices()
 * @method void setPyGenericServices()
 * @method array getUninterpretedOption()
 * @method void appendUninterpretedOption()
 *
 */
class FileOptions extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:google.protobuf.FileOptions)

  /** @var string $java_package tag:1  optional \ProtocolBuffers::TYPE_STRING */
  protected $java_package;

  /** @var string $java_outer_classname tag:8  optional \ProtocolBuffers::TYPE_STRING */
  protected $java_outer_classname;

  /** @var bool $java_multiple_files tag:10  optional \ProtocolBuffers::TYPE_BOOL */
  protected $java_multiple_files;

  /** @var bool $java_generate_equals_and_hash tag:20  optional \ProtocolBuffers::TYPE_BOOL */
  protected $java_generate_equals_and_hash;

  /** @var int $optimize_for tag:9  optional \ProtocolBuffers::TYPE_ENUM */
  protected $optimize_for;

  /** @var string $go_package tag:11  optional \ProtocolBuffers::TYPE_STRING */
  protected $go_package;

  /** @var bool $cc_generic_services tag:16  optional \ProtocolBuffers::TYPE_BOOL */
  protected $cc_generic_services;

  /** @var bool $java_generic_services tag:17  optional \ProtocolBuffers::TYPE_BOOL */
  protected $java_generic_services;

  /** @var bool $py_generic_services tag:18  optional \ProtocolBuffers::TYPE_BOOL */
  protected $py_generic_services;

  /** @var array $uninterpreted_option tag:999  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $uninterpreted_option = array();

  // @@protoc_insertion_point(properties_scope:google.protobuf.FileOptions)

  // @@protoc_insertion_point(class_scope:google.protobuf.FileOptions)

  /**
   * get descriptor for protocol buffers
   * 
   * @return ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;

    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "java_package",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(8, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "java_outer_classname",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(10, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "java_multiple_files",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => false,
      )));
      $desc->addField(20, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "java_generate_equals_and_hash",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => false,
      )));
      $desc->addField(9, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_ENUM,
        "name"     => "optimize_for",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => \google\protobuf\FileOptions\OptimizeMode::SPEED,
      )));
      $desc->addField(11, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "go_package",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(16, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "cc_generic_services",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => false,
      )));
      $desc->addField(17, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "java_generic_services",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => false,
      )));
      $desc->addField(18, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "py_generic_services",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => false,
      )));
      $desc->addField(999, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "uninterpreted_option",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\UninterpretedOption",
      )));
      $desc->addExtensionRange(1000, 536870912);
      // @@protoc_insertion_point(builder_scope:google.protobuf.FileOptions)

      $descriptor = $desc->build();
    }

    return $descriptor;
  }

}

