<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:google.protobuf.FileDescriptorProto)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method string getName()
 * @method void setName()
 * @method string getPackage()
 * @method void setPackage()
 * @method array getDependency()
 * @method void appendDependency()
 * @method array getPublicDependency()
 * @method void appendPublicDependency()
 * @method array getWeakDependency()
 * @method void appendWeakDependency()
 * @method array getMessageType()
 * @method void appendMessageType()
 * @method array getEnumType()
 * @method void appendEnumType()
 * @method array getService()
 * @method void appendService()
 * @method array getExtension()
 * @method void appendExtension()
 * @method \google\protobuf\FileOptions getOptions()
 * @method void setOptions()
 * @method \google\protobuf\SourceCodeInfo getSourceCodeInfo()
 * @method void setSourceCodeInfo()
 *
 */
class FileDescriptorProto extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:google.protobuf.FileDescriptorProto)

  /** @var string $name tag:1  optional \ProtocolBuffers::TYPE_STRING */
  protected $name;

  /** @var string $package tag:2  optional \ProtocolBuffers::TYPE_STRING */
  protected $package;

  /** @var array $dependency tag:3  optional \ProtocolBuffers::TYPE_STRING */
  protected $dependency = array();

  /** @var array $public_dependency tag:10  optional \ProtocolBuffers::TYPE_INT32 */
  protected $public_dependency = array();

  /** @var array $weak_dependency tag:11  optional \ProtocolBuffers::TYPE_INT32 */
  protected $weak_dependency = array();

  /** @var array $message_type tag:4  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $message_type = array();

  /** @var array $enum_type tag:5  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $enum_type = array();

  /** @var array $service tag:6  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $service = array();

  /** @var array $extension tag:7  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $extension = array();

  /** @var \google\protobuf\FileOptions $options tag:8  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $options;

  /** @var \google\protobuf\SourceCodeInfo $source_code_info tag:9  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $source_code_info;

  // @@protoc_insertion_point(properties_scope:google.protobuf.FileDescriptorProto)

  // @@protoc_insertion_point(class_scope:google.protobuf.FileDescriptorProto)

  /**
   * get descriptor for protocol buffers
   * 
   * @return ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;

    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "package",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "dependency",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(10, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "public_dependency",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => 0,
      )));
      $desc->addField(11, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "weak_dependency",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => 0,
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "message_type",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\DescriptorProto",
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "enum_type",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\EnumDescriptorProto",
      )));
      $desc->addField(6, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "service",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\ServiceDescriptorProto",
      )));
      $desc->addField(7, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "extension",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\FieldDescriptorProto",
      )));
      $desc->addField(8, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "options",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\FileOptions",
      )));
      $desc->addField(9, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "source_code_info",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\SourceCodeInfo",
      )));
      // @@protoc_insertion_point(builder_scope:google.protobuf.FileDescriptorProto)

      $descriptor = $desc->build();
    }

    return $descriptor;
  }

}

