<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:google.protobuf.FileDescriptorSet)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method array getFile()
 * @method void appendFile()
 *
 */
class FileDescriptorSet extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:google.protobuf.FileDescriptorSet)

  /** @var array $file tag:1  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $file = array();

  // @@protoc_insertion_point(properties_scope:google.protobuf.FileDescriptorSet)

  // @@protoc_insertion_point(class_scope:google.protobuf.FileDescriptorSet)

  /**
   * get descriptor for protocol buffers
   * 
   * @return ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;

    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "file",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\FileDescriptorProto",
      )));
      // @@protoc_insertion_point(builder_scope:google.protobuf.FileDescriptorSet)

      $descriptor = $desc->build();
    }

    return $descriptor;
  }

}

