<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:google.protobuf.MessageOptions)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method bool getMessageSetWireFormat()
 * @method void setMessageSetWireFormat()
 * @method bool getNoStandardDescriptorAccessor()
 * @method void setNoStandardDescriptorAccessor()
 * @method array getUninterpretedOption()
 * @method void appendUninterpretedOption()
 *
 */
class MessageOptions extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:google.protobuf.MessageOptions)

  /** @var bool $message_set_wire_format tag:1  optional \ProtocolBuffers::TYPE_BOOL */
  protected $message_set_wire_format;

  /** @var bool $no_standard_descriptor_accessor tag:2  optional \ProtocolBuffers::TYPE_BOOL */
  protected $no_standard_descriptor_accessor;

  /** @var array $uninterpreted_option tag:999  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $uninterpreted_option = array();

  // @@protoc_insertion_point(properties_scope:google.protobuf.MessageOptions)

  // @@protoc_insertion_point(class_scope:google.protobuf.MessageOptions)

  /**
   * get descriptor for protocol buffers
   * 
   * @return ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;

    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "message_set_wire_format",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => false,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "no_standard_descriptor_accessor",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => false,
      )));
      $desc->addField(999, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "uninterpreted_option",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\UninterpretedOption",
      )));
      $desc->addExtensionRange(1000, 536870912);
      // @@protoc_insertion_point(builder_scope:google.protobuf.MessageOptions)

      $descriptor = $desc->build();
    }

    return $descriptor;
  }

}

