<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:google.protobuf.MethodOptions)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method array getUninterpretedOption()
 * @method void appendUninterpretedOption()
 *
 */
class MethodOptions extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:google.protobuf.MethodOptions)

  /** @var array $uninterpreted_option tag:999  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $uninterpreted_option = array();

  // @@protoc_insertion_point(properties_scope:google.protobuf.MethodOptions)

  // @@protoc_insertion_point(class_scope:google.protobuf.MethodOptions)

  /**
   * get descriptor for protocol buffers
   * 
   * @return ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;

    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(999, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "uninterpreted_option",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\UninterpretedOption",
      )));
      $desc->addExtensionRange(1000, 536870912);
      // @@protoc_insertion_point(builder_scope:google.protobuf.MethodOptions)

      $descriptor = $desc->build();
    }

    return $descriptor;
  }

}

