<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:google.protobuf.ServiceDescriptorProto)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method string getName()
 * @method void setName()
 * @method array getMethod()
 * @method void appendMethod()
 * @method \google\protobuf\ServiceOptions getOptions()
 * @method void setOptions()
 *
 */
class ServiceDescriptorProto extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:google.protobuf.ServiceDescriptorProto)

  /** @var string $name tag:1  optional \ProtocolBuffers::TYPE_STRING */
  protected $name;

  /** @var array $method tag:2  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $method = array();

  /** @var \google\protobuf\ServiceOptions $options tag:3  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $options;

  // @@protoc_insertion_point(properties_scope:google.protobuf.ServiceDescriptorProto)

  // @@protoc_insertion_point(class_scope:google.protobuf.ServiceDescriptorProto)

  /**
   * get descriptor for protocol buffers
   * 
   * @return ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;

    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "method",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\MethodDescriptorProto",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "options",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\ServiceOptions",
      )));
      // @@protoc_insertion_point(builder_scope:google.protobuf.ServiceDescriptorProto)

      $descriptor = $desc->build();
    }

    return $descriptor;
  }

}

