<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:google.protobuf.UninterpretedOption)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method array getName()
 * @method void appendName()
 * @method string getIdentifierValue()
 * @method void setIdentifierValue()
 * @method string getPositiveIntValue()
 * @method void setPositiveIntValue()
 * @method string getNegativeIntValue()
 * @method void setNegativeIntValue()
 * @method string getDoubleValue()
 * @method void setDoubleValue()
 * @method string getStringValue()
 * @method void setStringValue()
 * @method string getAggregateValue()
 * @method void setAggregateValue()
 *
 */
class UninterpretedOption extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:google.protobuf.UninterpretedOption)

  /** @var array $name tag:2  optional \ProtocolBuffers::TYPE_MESSAGE */
  protected $name = array();

  /** @var string $identifier_value tag:3  optional \ProtocolBuffers::TYPE_STRING */
  protected $identifier_value;

  /** @var string $positive_int_value tag:4  optional \ProtocolBuffers::TYPE_UINT64 */
  protected $positive_int_value;

  /** @var string $negative_int_value tag:5  optional \ProtocolBuffers::TYPE_INT64 */
  protected $negative_int_value;

  /** @var string $double_value tag:6  optional \ProtocolBuffers::TYPE_DOUBLE */
  protected $double_value;

  /** @var string $string_value tag:7  optional \ProtocolBuffers::TYPE_BYTES */
  protected $string_value;

  /** @var string $aggregate_value tag:8  optional \ProtocolBuffers::TYPE_STRING */
  protected $aggregate_value;

  // @@protoc_insertion_point(properties_scope:google.protobuf.UninterpretedOption)

  // @@protoc_insertion_point(class_scope:google.protobuf.UninterpretedOption)

  /**
   * get descriptor for protocol buffers
   * 
   * @return ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;

    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "name",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message"  => "\\google\\protobuf\\UninterpretedOption\\NamePart",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "identifier_value",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_UINT64,
        "name"     => "positive_int_value",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => 0,
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "negative_int_value",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => 0,
      )));
      $desc->addField(6, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_DOUBLE,
        "name"     => "double_value",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => 0,
      )));
      $desc->addField(7, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BYTES,
        "name"     => "string_value",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(8, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "aggregate_value",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:google.protobuf.UninterpretedOption)

      $descriptor = $desc->build();
    }

    return $descriptor;
  }

}

