<?php
namespace google\protobuf\SourceCodeInfo;

// @@protoc_insertion_point(namespace:google.protobuf.SourceCodeInfo.Location)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method array getPath()
 * @method void appendPath()
 * @method array getSpan()
 * @method void appendSpan()
 * @method string getLeadingComments()
 * @method void setLeadingComments()
 * @method string getTrailingComments()
 * @method void setTrailingComments()
 *
 */
class Location extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:google.protobuf.SourceCodeInfo.Location)

  /** @var array $path tag:1  optional \ProtocolBuffers::TYPE_INT32 */
  protected $path = array();

  /** @var array $span tag:2  optional \ProtocolBuffers::TYPE_INT32 */
  protected $span = array();

  /** @var string $leading_comments tag:3  optional \ProtocolBuffers::TYPE_STRING */
  protected $leading_comments;

  /** @var string $trailing_comments tag:4  optional \ProtocolBuffers::TYPE_STRING */
  protected $trailing_comments;

  // @@protoc_insertion_point(properties_scope:google.protobuf.SourceCodeInfo.Location)

  // @@protoc_insertion_point(class_scope:google.protobuf.SourceCodeInfo.Location)

  /**
   * get descriptor for protocol buffers
   * 
   * @return ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;

    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "path",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => true,
        "default"  => 0,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "span",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => true,
        "default"  => 0,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "leading_comments",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "trailing_comments",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:google.protobuf.SourceCodeInfo.Location)

      $descriptor = $desc->build();
    }

    return $descriptor;
  }

}

