<?php
// @@protoc_insertion_point(namespace:PHPMessageOptions)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: php_options.proto
 *
 * -*- magic methods -*-
 *
 * @method bool getUseSingleProperty()
 * @method void setUseSingleProperty()
 * @method string getSinglePropertyName()
 * @method void setSinglePropertyName()
 * @method bool getUseWakeupAndSleep()
 * @method void setUseWakeupAndSleep()
 *
 */
class PHPMessageOptions extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:PHPMessageOptions)

  /** @var bool $use_single_property tag:2  optional \ProtocolBuffers::TYPE_BOOL */
  protected $use_single_property;

  /** @var string $single_property_name tag:3  optional \ProtocolBuffers::TYPE_STRING */
  protected $single_property_name;

  /** @var bool $use_wakeup_and_sleep tag:4  optional \ProtocolBuffers::TYPE_BOOL */
  protected $use_wakeup_and_sleep;

  // @@protoc_insertion_point(properties_scope:PHPMessageOptions)

  // @@protoc_insertion_point(class_scope:PHPMessageOptions)

  /**
   * get descriptor for protocol buffers
   * 
   * @return ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;

    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "use_single_property",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => false,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "single_property_name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "_properties",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "use_wakeup_and_sleep",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => false,
      )));
      // @@protoc_insertion_point(builder_scope:PHPMessageOptions)

      $descriptor = $desc->build();
    }

    return $descriptor;
  }

}
