<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:.google.protobuf.DescriptorProto)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method string getName()
 * @method void setName(string $value)
 * @method array getField()
 * @method void appendField(array $value)
 * @method array getExtension()
 * @method void appendExtension(array $value)
 * @method array getNestedType()
 * @method void appendNestedType(array $value)
 * @method array getEnumType()
 * @method void appendEnumType(array $value)
 * @method array getExtensionRange()
 * @method void appendExtensionRange(array $value)
 * @method \google\protobuf\MessageOptions getOptions()
 * @method void setOptions(\google\protobuf\MessageOptions $value)
 */
class DescriptorProto extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.google.protobuf.DescriptorProto)
  
  /** @var string $name tag:1  optional */
  protected $name;
  /** @var array $field tag:2  optional */
  protected $field;
  /** @var array $extension tag:6  optional */
  protected $extension;
  /** @var array $nested_type tag:3  optional */
  protected $nested_type;
  /** @var array $enum_type tag:4  optional */
  protected $enum_type;
  /** @var array $extension_range tag:5  optional */
  protected $extension_range;
  /** @var \google\protobuf\MessageOptions $options tag:7  optional */
  protected $options;
  
  // @@protoc_insertion_point(properties_scope:.google.protobuf.DescriptorProto)

  // @@protoc_insertion_point(class_scope:.google.protobuf.DescriptorProto)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "field",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => "\\google\\protobuf\\FieldDescriptorProto",
      )));
      $desc->addField(6, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "extension",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => "\\google\\protobuf\\FieldDescriptorProto",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "nested_type",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => "\\google\\protobuf\\DescriptorProto",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "enum_type",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => "\\google\\protobuf\\EnumDescriptorProto",
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "extension_range",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => "\\google\\protobuf\\DescriptorProto\\ExtensionRange",
      )));
      $desc->addField(7, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "options",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => "\\google\\protobuf\\MessageOptions",
      )));
      // @@protoc_insertion_point(builder_scope:.google.protobuf.DescriptorProto)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
