<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:.google.protobuf.FieldDescriptorProto)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method string getName()
 * @method void setName(string $value)
 * @method string getNumber()
 * @method void setNumber(string $value)
 * @method \google\protobuf\FieldDescriptorProto\Label getLabel()
 * @method void setLabel(\google\protobuf\FieldDescriptorProto\Label $value)
 * @method \google\protobuf\FieldDescriptorProto\Type getType()
 * @method void setType(\google\protobuf\FieldDescriptorProto\Type $value)
 * @method string getTypeName()
 * @method void setTypeName(string $value)
 * @method string getExtendee()
 * @method void setExtendee(string $value)
 * @method string getDefaultValue()
 * @method void setDefaultValue(string $value)
 * @method \google\protobuf\FieldOptions getOptions()
 * @method void setOptions(\google\protobuf\FieldOptions $value)
 */
class FieldDescriptorProto extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.google.protobuf.FieldDescriptorProto)
  
  /** @var string $name tag:1  optional */
  protected $name;
  /** @var string $number tag:3  optional */
  protected $number;
  /** @var \google\protobuf\FieldDescriptorProto\Label $label tag:4  optional */
  protected $label;
  /** @var \google\protobuf\FieldDescriptorProto\Type $type tag:5  optional */
  protected $type;
  /** @var string $type_name tag:6  optional */
  protected $type_name;
  /** @var string $extendee tag:2  optional */
  protected $extendee;
  /** @var string $default_value tag:7  optional */
  protected $default_value;
  /** @var \google\protobuf\FieldOptions $options tag:8  optional */
  protected $options;
  
  // @@protoc_insertion_point(properties_scope:.google.protobuf.FieldDescriptorProto)

  // @@protoc_insertion_point(class_scope:.google.protobuf.FieldDescriptorProto)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "number",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_ENUM,
        "name"     => "label",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_ENUM,
        "name"     => "type",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(6, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "type_name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "extendee",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(7, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "default_value",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(8, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "options",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => "\\google\\protobuf\\FieldOptions",
      )));
      // @@protoc_insertion_point(builder_scope:.google.protobuf.FieldDescriptorProto)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
