<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:.google.protobuf.FieldOptions)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method \google\protobuf\FieldOptions\CType getCtype()
 * @method void setCtype(\google\protobuf\FieldOptions\CType $value)
 * @method bool getPacked()
 * @method void setPacked(bool $value)
 * @method bool getLazy()
 * @method void setLazy(bool $value)
 * @method bool getDeprecated()
 * @method void setDeprecated(bool $value)
 * @method string getExperimentalMapKey()
 * @method void setExperimentalMapKey(string $value)
 * @method bool getWeak()
 * @method void setWeak(bool $value)
 * @method array getUninterpretedOption()
 * @method void appendUninterpretedOption(array $value)
 */
class FieldOptions extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.google.protobuf.FieldOptions)
  
  /** @var \google\protobuf\FieldOptions\CType $ctype tag:1  optional */
  protected $ctype;
  /** @var bool $packed tag:2  optional */
  protected $packed;
  /** @var bool $lazy tag:5  optional */
  protected $lazy;
  /** @var bool $deprecated tag:3  optional */
  protected $deprecated;
  /** @var string $experimental_map_key tag:9  optional */
  protected $experimental_map_key;
  /** @var bool $weak tag:10  optional */
  protected $weak;
  /** @var array $uninterpreted_option tag:999  optional */
  protected $uninterpreted_option;
  
  // @@protoc_insertion_point(properties_scope:.google.protobuf.FieldOptions)

  // @@protoc_insertion_point(class_scope:.google.protobuf.FieldOptions)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_ENUM,
        "name"     => "ctype",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => \google\protobuf\FieldOptions\CType::STRING,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "packed",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => false,
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "lazy",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => true,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "deprecated",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => true,
      )));
      $desc->addField(9, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "experimental_map_key",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(10, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "weak",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => true,
      )));
      $desc->addField(999, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "uninterpreted_option",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => "\\google\\protobuf\\UninterpretedOption",
      )));
      // @@protoc_insertion_point(builder_scope:.google.protobuf.FieldOptions)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
