<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:.google.protobuf.FileOptions)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method string getJavaPackage()
 * @method void setJavaPackage(string $value)
 * @method string getJavaOuterClassname()
 * @method void setJavaOuterClassname(string $value)
 * @method bool getJavaMultipleFiles()
 * @method void setJavaMultipleFiles(bool $value)
 * @method bool getJavaGenerateEqualsAndHash()
 * @method void setJavaGenerateEqualsAndHash(bool $value)
 * @method \google\protobuf\FileOptions\OptimizeMode getOptimizeFor()
 * @method void setOptimizeFor(\google\protobuf\FileOptions\OptimizeMode $value)
 * @method string getGoPackage()
 * @method void setGoPackage(string $value)
 * @method bool getCcGenericServices()
 * @method void setCcGenericServices(bool $value)
 * @method bool getJavaGenericServices()
 * @method void setJavaGenericServices(bool $value)
 * @method bool getPyGenericServices()
 * @method void setPyGenericServices(bool $value)
 * @method array getUninterpretedOption()
 * @method void appendUninterpretedOption(array $value)
 */
class FileOptions extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.google.protobuf.FileOptions)
  
  /** @var string $java_package tag:1  optional */
  protected $java_package;
  /** @var string $java_outer_classname tag:8  optional */
  protected $java_outer_classname;
  /** @var bool $java_multiple_files tag:10  optional */
  protected $java_multiple_files;
  /** @var bool $java_generate_equals_and_hash tag:20  optional */
  protected $java_generate_equals_and_hash;
  /** @var \google\protobuf\FileOptions\OptimizeMode $optimize_for tag:9  optional */
  protected $optimize_for;
  /** @var string $go_package tag:11  optional */
  protected $go_package;
  /** @var bool $cc_generic_services tag:16  optional */
  protected $cc_generic_services;
  /** @var bool $java_generic_services tag:17  optional */
  protected $java_generic_services;
  /** @var bool $py_generic_services tag:18  optional */
  protected $py_generic_services;
  /** @var array $uninterpreted_option tag:999  optional */
  protected $uninterpreted_option;
  
  // @@protoc_insertion_point(properties_scope:.google.protobuf.FileOptions)

  // @@protoc_insertion_point(class_scope:.google.protobuf.FileOptions)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "java_package",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(8, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "java_outer_classname",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(10, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "java_multiple_files",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => true,
      )));
      $desc->addField(20, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "java_generate_equals_and_hash",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => true,
      )));
      $desc->addField(9, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_ENUM,
        "name"     => "optimize_for",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => \google\protobuf\FileOptions\OptimizeMode::SPEED,
      )));
      $desc->addField(11, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "go_package",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(16, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "cc_generic_services",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => true,
      )));
      $desc->addField(17, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "java_generic_services",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => true,
      )));
      $desc->addField(18, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "py_generic_services",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => true,
      )));
      $desc->addField(999, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "uninterpreted_option",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => "\\google\\protobuf\\UninterpretedOption",
      )));
      // @@protoc_insertion_point(builder_scope:.google.protobuf.FileOptions)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
