<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:.google.protobuf.FileDescriptorSet)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * The protocol compiler can output a FileDescriptorSet containing the .proto
 * files it parses.
 *
 * -*- magic methods -*-
 *
 * @method array getFile()
 * @method void appendFile(\google\protobuf\FileDescriptorProto $value)
 */
class FileDescriptorSet extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.google.protobuf.FileDescriptorSet)
  
  /**
   * @var array $file
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \google\protobuf\FileDescriptorProto
   **/
  protected $file;
  
  
  // @@protoc_insertion_point(properties_scope:.google.protobuf.FileDescriptorSet)

  // @@protoc_insertion_point(class_scope:.google.protobuf.FileDescriptorSet)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "file",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\google\protobuf\FileDescriptorProto',
      )));
      // @@protoc_insertion_point(builder_scope:.google.protobuf.FileDescriptorSet)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
