<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:.google.protobuf.MessageOptions)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * -*- magic methods -*-
 *
 * @method bool getMessageSetWireFormat()
 * @method void setMessageSetWireFormat(bool $value)
 * @method bool getNoStandardDescriptorAccessor()
 * @method void setNoStandardDescriptorAccessor(bool $value)
 * @method array getUninterpretedOption()
 * @method void appendUninterpretedOption(array $value)
 */
class MessageOptions extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.google.protobuf.MessageOptions)
  
  /** @var bool $message_set_wire_format tag:1  optional */
  protected $message_set_wire_format;
  /** @var bool $no_standard_descriptor_accessor tag:2  optional */
  protected $no_standard_descriptor_accessor;
  /** @var array $uninterpreted_option tag:999  optional */
  protected $uninterpreted_option;
  
  // @@protoc_insertion_point(properties_scope:.google.protobuf.MessageOptions)

  // @@protoc_insertion_point(class_scope:.google.protobuf.MessageOptions)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "message_set_wire_format",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => true,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_BOOL,
        "name"     => "no_standard_descriptor_accessor",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => true,
      )));
      $desc->addField(999, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "uninterpreted_option",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => "\\google\\protobuf\\UninterpretedOption",
      )));
      // @@protoc_insertion_point(builder_scope:.google.protobuf.MessageOptions)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
