<?php
namespace google\protobuf;

// @@protoc_insertion_point(namespace:.google.protobuf.ServiceDescriptorProto)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 * Describes a service.
 *
 * -*- magic methods -*-
 *
 * @method string getName()
 * @method void setName(string $value)
 * @method array getMethod()
 * @method void appendMethod(\google\protobuf\MethodDescriptorProto $value)
 * @method \google\protobuf\ServiceOptions getOptions()
 * @method void setOptions(\google\protobuf\ServiceOptions $value)
 */
class ServiceDescriptorProto extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.google.protobuf.ServiceDescriptorProto)
  
  /**
   * @var string $name
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $name;
  
  /**
   * @var array $method
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \google\protobuf\MethodDescriptorProto
   **/
  protected $method;
  
  /**
   * @var \google\protobuf\ServiceOptions $options
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $options;
  
  
  // @@protoc_insertion_point(properties_scope:.google.protobuf.ServiceDescriptorProto)

  // @@protoc_insertion_point(class_scope:.google.protobuf.ServiceDescriptorProto)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "method",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\google\protobuf\MethodDescriptorProto',
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "options",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\google\protobuf\ServiceOptions',
      )));
      // @@protoc_insertion_point(builder_scope:.google.protobuf.ServiceDescriptorProto)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
