<?php
namespace google\protobuf\FieldOptions;

// @@protoc_insertion_point(namespace:.google.protobuf.FieldOptions.CType)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 */
class CType
{
  const STRING = 0;
  const CORD = 1;
  const STRING_PIECE = 2;
}
