<?php
namespace protocolbuffers\generator\php;

use protocolbuffers\io\Printer;

class MessageGenerator
{
    protected $file;
    protected $descriptor;

    public function __construct(\google\protobuf\FileDescriptorProto $file, \google\protobuf\DescriptorProto $descriptor)
    {
        $this->file = $file;
        $this->descriptor = $descriptor;
    }

    public function printProperties(Printer $printer)
    {
        foreach ($this->descriptor->getField() as $field) {
            /* @var $field \google\protobuf\FieldDescriptorProto */
            $printer->put("protected \$`name`;\n",
                "name",
                $field->getName()
            );
        }

        $printer->put("// @@protoc_insertion_point(properties_scope:`name`)\n\n",
            "name", $this->descriptor->getName()
        );

    }

    public function printGetDescriptor(Printer $printer)
    {
        $printer->put("/**\n");
        $printer->put(" * get descriptor for protocol buffers\n");
        $printer->put(" * \n");
        $printer->put(" * @return ProtocolBuffersDescriptor\n");
        $printer->put(" */\n");
        $printer->put("public static function getDescriptor()\n");
        $printer->put("{\n");
        $printer->indent();
        $printer->put("static \$descriptor;\n");
        $printer->put("\n");
        $printer->put("if (!isset(\$descriptor)) {\n");
        $printer->indent();
        $printer->put("\$desc = new `class_name`();\n",
            "class_name",
            "\\ProtocolBuffers\\DescriptorBuilder");

        foreach ($this->descriptor->getField() as $offset => $field) {
            /* @var $field \google\protobuf\FieldDescriptorProto */
            $printer->put("\$desc->addField(`tag`, new `class_name`(array(\n",
                "tag",
                $field->getNumber(),
                "class_name",
                "\\ProtocolBuffers\\FieldDescriptor");
            $printer->indent();
            $printer->put("\"type\"     => `type`,\n",
                "type",
                $field->getType());
            $printer->put("\"name\"     => \"`name`\",\n",
                "name",
                $field->getName());
            $printer->put("\"required\" => `required`,\n",
                "required",
                ($field->getLabel() == \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED) ? "true" : "false");
            $printer->put("\"optional\" => `optional`,\n",
                "optional",
                ($field->getLabel() == \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL) ? "true" : "false");
            $printer->put("\"repeated\" => `repeated`,\n",
                "repeated",
                ($field->getLabel() == \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED) ? "true" : "false");
            $printer->put("\"packable\" => `packable`,\n",
                "packable",
                ($field->getLabel() == \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED &&
                    $field->getOptions()->getPacked()) ? "true" : "false");
            $printer->put("\"default\"  => \"`value`\",\n",
                "value",
                $field->getDefaultValue());

            if ($field->getType() == \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE) {
                $name = $field->getTypeName();
                $descriptor = null;
                foreach ($this->file->getMessageType() as $m) {
                    if ("." . $m->getName() == $name){
                        $descriptor = $m;
                        break;

                    }
                }
                $printer->put("\"message\" => \"`message`\",\n",
                    "message",
                    $descriptor->getName()
                );
            }

            $printer->outdent();
            $printer->put(")));\n");
        }

        $printer->put("// @@protoc_insertion_point(builder_scope:`name`)\n\n",
            "name", $this->descriptor->getName());

        $printer->put("\$descriptor = \$desc->build();\n");
        $printer->outdent();
        $printer->put("}\n");

        $printer->put("return \$descriptor;\n");
        $printer->outdent();
        $printer->put("}\n\n");
    }

    public function generate(Printer $printer)
    {
        $printer->put("<?php\n");
        $printer->put(
            "/**\n" .
            " * Generated by the protocol buffer compiler.  DO NOT EDIT!\n" .
            " * source: `filename`\n" .
            " *\n",
            "filename",
            ""
        );
        $printer->put(" */\n");

        $printer->put("class `name` extends \\ProtocolBuffers\\Message\n{\n",
            "name",
            $this->descriptor->getName()
        );
        $printer->indent();
        $this->printProperties($printer);
        $this->printGetDescriptor($printer);

        $printer->outdent();
        $printer->put("}\n");
    }
}

