<?php
namespace google\protobuf\FieldDescriptorProto;

// @@protoc_insertion_point(namespace:.google.protobuf.FieldDescriptorProto.Label)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/descriptor.proto
 *
 */
class Label
{
  const LABEL_OPTIONAL = 1;
  const LABEL_REQUIRED = 2;
  const LABEL_REPEATED = 3;
}
