<?php
namespace google\protobuf\compiler\CodeGeneratorResponse;

// @@protoc_insertion_point(namespace:google.protobuf.compiler.CodeGeneratorResponse.File)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: google/protobuf/compiler/plugin.proto
 *
 * -*- magic methods -*-
 *
 * @method string getName()
 * @method void setName()
 * @method string getInsertionPoint()
 * @method void setInsertionPoint()
 * @method string getContent()
 * @method void setContent()
 *
 */
class File extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:google.protobuf.compiler.CodeGeneratorResponse.File)

  /** @var string $name tag:1  optional \ProtocolBuffers::TYPE_STRING */
  protected $name;

  /** @var string $insertion_point tag:2  optional \ProtocolBuffers::TYPE_STRING */
  protected $insertion_point;

  /** @var string $content tag:15  optional \ProtocolBuffers::TYPE_STRING */
  protected $content;

  // @@protoc_insertion_point(properties_scope:google.protobuf.compiler.CodeGeneratorResponse.File)

  // @@protoc_insertion_point(class_scope:google.protobuf.compiler.CodeGeneratorResponse.File)

  /**
   * get descriptor for protocol buffers
   * 
   * @return ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;

    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "name",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "insertion_point",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(15, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "content",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:google.protobuf.compiler.CodeGeneratorResponse.File)

      $descriptor = $desc->build();
    }

    return $descriptor;
  }

}

